### ISSUE TITLE
Missing stream dependency?

### ISSUE THREAD

**Issue by Blutude** [j0x0j/base64-string-s3#3]
I am getting the following error "Module `stream` does not exist in the Haste module map"

Does "npm install stream" fix this? I might be downloading the wrong package?

**Comment by j0x0j** [comment]
I don't think that error is related to this module. I just updated dependencies and tested in node v8.x and can't seem to replicate it. Can you provide some more context and a sample of how you are using it?

**Comment by Blutude** [comment]
In your putter.js file, you have `var stream = require('stream')` and `var util = require('util')`
I didn't have these in my project so these lines would give me the error "Module stream does not exist in the Haste module map"

**Comment by j0x0j** [comment]
Oh, are you trying to run it in the browser or in a NodeJS program?

**Comment by Blutude** [comment]
My bad, I somehow assumed this was for react native..

**Comment by j0x0j** [comment]
No problem, happy to help. I'll think about use cases other than server side.
